# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x360', '0002_game_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
